language: elixir

env:
  - MIX_ENV=test

install:
  - mix do local.hex --force, local.rebar --force
  - mix deps.get
  - mix compile

script:
  - mix test

# https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp
jobs:
  include:
    # Elixir 1.7: 19-22
    - elixir: "1.7"
      otp_relase: "19.0"

    - elixir: "1.7"
      otp_relase: "20.0"

    - elixir: "1.7"
      otp_relase: "21.0"

    - elixir: "1.7"
      otp_relase: "22.0"

    # Elixir 1.8: 20-22
    - elixir: "1.8"
      otp_relase: "20.0"

    - elixir: "1.8"
      otp_relase: "21.0"

    - elixir: "1.8"
      otp_relase: "22.0"

    # Elixir 1.9: 20-22
    - elixir: "1.9"
      otp_relase: "20.0"

    - elixir: "1.9"
      otp_relase: "21.0"

    - elixir: "1.9"
      otp_relase: "22.0"

    # Elixir 1.10: 21-22
    - elixir: "1.10"
      otp_relase: "21.0"

    - elixir: "1.10"
      otp_relase: "22.0"

    # Elixir 1.11: 21-23
    - elixir: "1.11"
      otp_relase: "21.0"

    - elixir: "1.11"
      otp_relase: "22.0"

    - elixir: "1.11"
      otp_relase: "23.0"
